### ISSUE TITLE
nvidia-smi is not working at

### ISSUE THREAD

**Issue by grandfatheryun** [CryptoTuner/CryptoTuner#1]

**Comment by grandfatheryun** [comment]
can you tell me how do you overclock the mem clock?

**Comment by CryptoTuner** [comment]
> can you tell me how do you overclock the mem clock?

Hello and thank you for trying my tool.

So you got a message that says nvidia-smi is not working?
What graphic drivers do you have installed?

**Comment by grandfatheryun** [comment]
456.71

**Comment by CryptoTuner** [comment]
> 456.71

Can you upload the log file?

**Comment by grandfatheryun** [comment]
i haven't use your tool,but if i cloudn't use nvidia-smi -ac to set my gpu mem clock,so yours cloudn't

**Comment by CryptoTuner** [comment]
> i haven't use your tool,but if i cloudn't use nvidia-smi -ac to set my gpu mem clock,so yours cloudn't

My tool does not depend on nvidia-smi for setting the OC. It only uses it for reading data from the GPU

**Comment by CryptoTuner** [comment]
Closing as there is not really a bug
